###

POST http://localhost:3000/users/
Content-Type: application/json

{    
    "name":"rahul",
    "username":"rahul143",
   
    "password": "rahul@423",
    "gender": "Male",
    "location":"hyderabad"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"rahul143",
    "password": "rahul@423"
}